# Generated by Django 2.2 on 2020-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Armor', 'Armor'), ('Weapons', 'Weapons'), ('Ingredients', 'Ingredients'), ('Other', 'Other')], default='Other', max_length=20)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('width', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='item_images')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
