# Generated by Django 2.2 on 2020-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
