# Generated by Django 2.2 on 2020-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Armor', 'Armor'), ('Weapons', 'Weapons'), ('Potions', 'Potions'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
